server {
    listen 80;
    server_name k14s307.p.ssafy.io;
    return 301 https://$host$request_uri;  # HTTP → HTTPS 리다이렉트
}

server {
    listen 443 ssl;
    server_name k14s307.p.ssafy.io;

    ssl_certificate /etc/letsencrypt/live/k14s307.p.ssafy.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/k14s307.p.ssafy.io/privkey.pem;

    client_max_body_size 500m;

    location / {
        proxy_pass http://gemmark-fe:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_pass http://gemmark-be:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /docs {
        proxy_pass http://gemmark-be:8000/docs;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /openapi.json {
        proxy_pass http://gemmark-be:8000/openapi.json;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /files/ {
        proxy_pass http://gemmark-be:8000/files/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_buffering off;
        proxy_max_temp_file_size 0;
        add_header Accept-Ranges bytes;
        proxy_set_header Range $http_range;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}