server {
    listen 80;

    # FE 요청
    location / {
        proxy_pass http://gemmark-fe:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # BE API 요청
    location /api/ {
        proxy_pass http://gemmark-be:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}